In [2]:
import numpy as np

In [3]:
A = np.array([[5, 1],
            [3, 3]])

In [4]:
eigVals, eigVecs = np.linalg.eig(A)

In [5]:
eigVals

array([6., 2.])

In [6]:
eigVecs

array([[ 0.70710678, -0.31622777],
       [ 0.70710678,  0.9486833 ]])

In [7]:
v1 = eigVecs[:, 0]
v2 = eigVecs[:, 1]

In [8]:
print(np.linalg.norm(v1))
print(np.linalg.norm(v2))

0.9999999999999999
0.9999999999999999


In [9]:
np.dot(v1, v2)

0.44721359549995787

In [9]:
np.linalg.matrix_rank(A)

2

In [12]:
B = np.array([[-5, 1],
            [3, -3]])

In [13]:
np.linalg.eig(B)

(array([-6., -2.]), array([[-0.70710678, -0.31622777],
        [ 0.70710678, -0.9486833 ]]))

In [10]:
C = np.array([[1, 2],
            [2, 1]])

In [12]:
evalues, evectors = np.linalg.eig(C)

대칭행렬의 고유벡터는 서로 수직

In [13]:
np.dot(evectors[:,0], evectors[:,1])

0.0

## 모든 고유값이 0보다 큰지 작은지 test

In [17]:
np.all(np.linalg.eigvals(C) > 0)

False

# Eigendecomposition

In [18]:
A = np.array([[5, 1],
            [3, 3]])

In [19]:
eigVals, eigVecs = np.linalg.eig(A)

In [20]:
V = eigVecs

In [21]:
L = np.diag(eigVals)

In [22]:
L

array([[6., 0.],
       [0., 2.]])

eigendecomposition

In [24]:
np.dot(V, L).dot(np.linalg.inv(V))

array([[5., 1.],
       [3., 3.]])

### When A is a symmetric matrix, then A-1 = A.T

In [25]:
C = np.array([[5, 1],
            [1, 3]])

In [26]:
eigVals1, eigVecs1 = np.linalg.eig(C)

In [29]:
eigVecs1.T

array([[ 0.92387953,  0.38268343],
       [-0.38268343,  0.92387953]])

In [30]:
np.linalg.inv(eigVecs1)

array([[ 0.92387953,  0.38268343],
       [-0.38268343,  0.92387953]])