In [24]:
import pandas as pd
import numpy as np
import pickle

In [25]:
df_result = pd.read_pickle('df_result.pkl')
df_test = pd.read_pickle('df_test.pkl')
with open('word_index.pkl', 'rb') as pkl_file:
    vocab_dict = pickle.load(pkl_file)

In [26]:
vocab_list = [x for x in range(len(vocab_dict)+1)]
for k,v in vocab_dict.items():
    vocab_list[v] = k

In [27]:
df_test = df_test.head(len(df_result)).reset_index(drop=True)
# df_test.x = df_test.x.apply(lambda x: x.split())
df_test = df_test.rename({'x': 'origin_tokens'}, axis=1)

In [28]:
pd.Series(df_result.y == df_test.y).unique()

array([ True])

In [29]:
len(df_test)

19200

In [30]:
df = pd.concat([df_result, df_test.drop(['y'], axis=1)], axis=1)

In [31]:
df['tokens'] = df.x.apply(lambda x_list: [vocab_list[x] for x in x_list])

In [32]:
df[['text', 'y', 'pred']].head(20)

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>text</th>
      <th>y</th>
      <th>pred</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>빠른 배송 감사하지만, 제품은 그냥저냥 그래요.\r\n가격을 감안하면 수긍은 갑니다...</td>
      <td>0</td>
      <td>1</td>
    </tr>
    <tr>
      <th>1</th>
      <td>항상 쓰던거야 구매요\r\n직구라 배송 시간을 좀 걸렸지만..\r\n잘쓰고 있어요</td>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <th>2</th>
      <td>따뜻하고 좋네요..사이즈는 좀 크게 나와서 넉넉하게 입을 수 있어요</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>3</th>
      <td>헉~~\n배송 받아서 한 번 사용해봐야지~~\n퍼프에서 검은 가루가 떨어져서 팩트에...</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>4</th>
      <td>품이 큽니다. 넉넉하게 나왔어요. 한 치수 작게 주문해도 될 듯합니다.</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>5</th>
      <td>초밀착되고 정말 안바른것처럼 가벼워서 좋아요. 처음엔 바르면서 너무 안바른듯한 느낌...</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>6</th>
      <td>주문해놓고 피부가 예민한편이라 무료체험도 없고해서 \n망설이다가 아직 못써봤는데 상...</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>7</th>
      <td>구매후\r\n일주일만에\r\n투어리스트로고가\r\n어디로갔는지\r\n없어졌습니다\r...</td>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <th>8</th>
      <td>색상마다 사이즈가 약간씩 차이가 있습니다 \r\n55이상인 사람들이 입기엔 작아요 ...</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>9</th>
      <td>반나절 입었는데 보플이 장난아니네요\n두벌값으로 한벌 살걸 잘못했네요</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>10</th>
      <td>발볼이 있는편이라 한치수크게 주문했는데 \r\n그래도발볼이쪼이네요 디자인은 무난해요...</td>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <th>11</th>
      <td>가격도 괜찬아서 구매했구 배송도 빨라서 좋았는데 아무리 그래도 새 제품인데 스크래치...</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>12</th>
      <td>따뜻해서 굿\r\n부드러워굿\r\n요즘 데일리옷입네당</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>13</th>
      <td>완전 맘에 들어요. 겨울  바지도 나오면 좋을텐데.</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>14</th>
      <td>폭신하고 부드러워요. 20센티정도 작아요.</td>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <th>15</th>
      <td>포징도 디자인도 다 200점.\r\n고풍스러우면서 소박한 서민적인 느낌 골고루 갖고...</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>16</th>
      <td>너무조아요 커버력도좋고 얇게발리는 느낌이</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>17</th>
      <td>고급스럽다는 느낌은 없음\n밥맛은 보통</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>18</th>
      <td>두께가 얇아서 뾱뾱이가 잘터져요 가격대비 한겨울 쓰기에는 그냥그냥 담엔 좀 두꺼운걸...</td>
      <td>0</td>
      <td>1</td>
    </tr>
    <tr>
      <th>19</th>
      <td>가슴아랫부분이 말려 올라가긴 하는데...편하기도 합니다.</td>
      <td>1</td>
      <td>0</td>
    </tr>
  </tbody>
</table>
</div>

In [33]:
def get_max_args(row):
    alpha = np.array(row['alpha'])
    x =  np.array(row['x'])
    zero_index = np.where(x == 0)[0].tolist()
    if zero_index:
        sent_size = int(zero_index[0])
    else:
        sent_size = int(len(x))
    num_alpha = int(sent_size / 3) + 1
    alpha = alpha[:sent_size].argsort()[-num_alpha:][::-1]
    return alpha.tolist()


df['max_args'] = df.apply(lambda row: get_max_args(row), axis=1)

In [34]:
print(np.argsort([1, 3, 2, 4, 5]))
print(np.argsort([1, 3, 2, 4, 5])[-3:])
print(np.argsort([1, 3, 2, 4, 5])[-3:][::-1])

print(np.where(np.array([1,3] )== 0)[0])
# 1 2 0 / 2 0 1

[0 2 1 3 4]
[1 3 4]
[4 3 1]
[]


In [35]:
df.x.values[0]

array([  45,   18,   72,   16,  110,   14, 1219,  105,   10,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
      dtype=int32)

In [36]:
df[['tokens', 'x','max_args']].head(20)

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>tokens</th>
      <th>x</th>
      <th>max_args</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>[빠르, 배송, 감사, 제품, 그러, 가격, 감안, 가, 구매, 0, 0, 0, 0...</td>
      <td>[45, 18, 72, 16, 110, 14, 1219, 105, 10, 0, 0,...</td>
      <td>[6, 7, 5, 4]</td>
    </tr>
    <tr>
      <th>1</th>
      <td>[쓸, 것, 이, 구매, 이, 직구, 이, 배송, 시간, 걸리, 쓸, 있, 0, 0...</td>
      <td>[12, 4, 1, 10, 1, 1853, 1, 18, 183, 307, 12, 5...</td>
      <td>[7, 8, 10, 9, 5]</td>
    </tr>
    <tr>
      <th>2</th>
      <td>[따뜻, 좋, 사이즈, 크, 나오, 넉넉, 입, 수, 있, 0, 0, 0, 0, 0...</td>
      <td>[31, 2, 15, 19, 60, 158, 7, 41, 5, 0, 0, 0, 0,...</td>
      <td>[8, 7, 4, 5]</td>
    </tr>
    <tr>
      <th>3</th>
      <td>[배송, 받, 번, 사용, 보, 하, 퍼프, 검, 가루, 떨어지, 트, 붙, 있, ...</td>
      <td>[18, 32, 27, 11, 6, 3, 504, 1141, 1198, 169, 8...</td>
      <td>[17, 16, 0, 9, 8, 7, 1]</td>
    </tr>
    <tr>
      <th>4</th>
      <td>[품, 크, 넉넉, 나오, 치수, 작, 주문, 되, 듯, 0, 0, 0, 0, 0,...</td>
      <td>[91, 19, 158, 60, 264, 54, 25, 13, 26, 0, 0, 0...</td>
      <td>[3, 1, 2, 4]</td>
    </tr>
    <tr>
      <th>5</th>
      <td>[밀착, 바르, 것, 가볍, 좋, 처음, 바르, 바르, 듯, 느낌, 이, 좋, 나쁘...</td>
      <td>[500, 70, 4, 61, 2, 119, 70, 70, 26, 53, 1, 2,...</td>
      <td>[22, 25, 20, 24, 26, 13, 21, 14, 15, 29, 18]</td>
    </tr>
    <tr>
      <th>6</th>
      <td>[주문, 놓, 피부, 예민, 편, 이, 무료, 체험, 없, 하, 망설이, 쓰, 보,...</td>
      <td>[25, 149, 57, 920, 129, 1, 549, 434, 20, 3, 60...</td>
      <td>[24, 25, 26, 23, 22, 20, 21, 19, 18, 9]</td>
    </tr>
    <tr>
      <th>7</th>
      <td>[구매, 후, 일, 주일, 만, 고가, 어디, 가, 없, 지, 불량, 보내, 주, ...</td>
      <td>[10, 104, 99, 484, 141, 1551, 568, 105, 20, 21...</td>
      <td>[30, 31, 29, 24, 28, 26, 23, 27, 25, 20, 16]</td>
    </tr>
    <tr>
      <th>8</th>
      <td>[색상, 사이즈, 차이, 있, 55, 이상, 이, 사람, 입, 작, free, 사이...</td>
      <td>[48, 15, 375, 5, 214, 200, 1, 233, 7, 54, 2851...</td>
      <td>[15, 14, 13, 11, 12, 1]</td>
    </tr>
    <tr>
      <th>9</th>
      <td>[반, 나절, 입, 보, 프, 장난, 아니, 두, 벌, 값, 벌, 사, 것, 하, ...</td>
      <td>[278, 2455, 7, 6, 632, 589, 50, 187, 468, 666,...</td>
      <td>[13, 12, 11, 10, 9]</td>
    </tr>
    <tr>
      <th>10</th>
      <td>[발, 볼, 있, 편, 이, 치수, 크, 주문, 그러, 발, 볼, 쪼이, 디자인, ...</td>
      <td>[67, 337, 5, 129, 1, 264, 19, 25, 110, 67, 337...</td>
      <td>[15, 14, 12, 16, 18, 13, 17, 19, 20, 21]</td>
    </tr>
    <tr>
      <th>11</th>
      <td>[가격, 괜찬아서, 구매, 배송, 빠르, 좋, 그래도, 제품, 이, 스크래치, 심하...</td>
      <td>[14, 4771, 10, 18, 45, 2, 352, 16, 1, 1590, 20...</td>
      <td>[13, 12, 10, 14, 15, 11]</td>
    </tr>
    <tr>
      <th>12</th>
      <td>[따뜻, 굿, 부드럽, 굿, 요, 즘, 데일리, 옷, 이, 당, 0, 0, 0, 0...</td>
      <td>[31, 115, 62, 115, 267, 437, 868, 37, 1, 1049,...</td>
      <td>[9, 7, 8, 0]</td>
    </tr>
    <tr>
      <th>13</th>
      <td>[완전, 맘, 듣, 겨울, 바지, 나오, 좋, 터, 이, 0, 0, 0, 0, 0,...</td>
      <td>[146, 30, 29, 44, 87, 60, 2, 327, 1, 0, 0, 0, ...</td>
      <td>[7, 8, 0, 6]</td>
    </tr>
    <tr>
      <th>14</th>
      <td>[하, 부드럽, 20, 센티, 정도, 작, 0, 0, 0, 0, 0, 0, 0, 0...</td>
      <td>[3, 62, 582, 1087, 82, 54, 0, 0, 0, 0, 0, 0, 0...</td>
      <td>[0, 4, 5]</td>
    </tr>
    <tr>
      <th>15</th>
      <td>[디자인, 200, 점, 이, 느낌, 갖, 있, 듯, 하, 은근, 매력, 있, 무게...</td>
      <td>[33, 1346, 221, 1, 53, 687, 5, 26, 3, 1757, 18...</td>
      <td>[8, 9, 1, 0, 12, 10]</td>
    </tr>
    <tr>
      <th>16</th>
      <td>[조아, 이, 크, 버력, 좋, 얇, 발리, 느낌, 0, 0, 0, 0, 0, 0,...</td>
      <td>[311, 1, 19, 241, 2, 76, 548, 53, 0, 0, 0, 0, ...</td>
      <td>[7, 6, 5]</td>
    </tr>
    <tr>
      <th>17</th>
      <td>[고급, 느낌, 없, 밥, 맛, 보통, 0, 0, 0, 0, 0, 0, 0, 0, ...</td>
      <td

In [37]:
def get_alpha_tokens(row):
    max_args = row['max_args']
    xs = row['x']
    tokens = row['tokens']
    alpha_tokens = list()
    try:
        alpha_tokens = [tokens[arg] for arg in max_args if xs[arg] != 0]
    except IndexError:
        print("IndexError")
        alpha_tokens = None
    finally:
        return alpha_tokens

df['alpha_tokens'] = df.apply(lambda row: get_alpha_tokens(row), axis=1)

In [49]:
df.loc[2741, 'text']

'■° 버건디 칼라 괜찮아서,  하나 더 구매 합니다~*  다만, 기모가 엄청 엄청 묻어나요~, 세탁해도 빠진 다는 것이 함정!'

In [39]:
df['correct'] = (df.y == df.pred)

In [47]:
df.loc[:, ['text', 'alpha_tokens', 'tokens', 'max_args', 'y', 'pred']].sample(15)

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>text</th>
      <th>alpha_tokens</th>
      <th>tokens</th>
      <th>max_args</th>
      <th>y</th>
      <th>pred</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>5449</th>
      <td>생활 곳곳에 필수템으로 구성이 좋네요</td>
      <td>[좋, 곳, 필수]</td>
      <td>[생활, 곳, 곳, 필수, 템, 구성, 좋, 0, 0, 0, 0, 0, 0, 0, ...</td>
      <td>[6, 2, 3]</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>13421</th>
      <td>배송 빠르고 하자 없이 잘 도착해서 너무 마음에 듭니다.\n전 시즌 쿠션보다 훨씬 ...</td>
      <td>[듣, 지, 맘, 좋, 버력, 크, 제품]</td>
      <td>[배송, 빠르, 하, 도착, 마음, 듭니다, 시즌, 쿠션, 만족, 구매, 의사, 생...</td>
      <td>[19, 17, 18, 16, 15, 14, 13]</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>8828</th>
      <td>더 크게 나왔으면 좋을듯\n세척  간편해요</td>
      <td>[세척, 간편, 듯]</td>
      <td>[크, 나오, 좋, 듯, 세척, 간편, 0, 0, 0, 0, 0, 0, 0, 0, ...</td>
      <td>[4, 5, 3]</td>
      <td>0</td>
      <td>1</td>
    </tr>
    <tr>
      <th>11575</th>
      <td>털이 풍성해서 따뜻하고 폭신폭신해요~~~\n백화점 가격의 반가격에 구입했네요^^</td>
      <td>[구입, 가격, 반, 가격]</td>
      <td>[털, 풍성, 따뜻, 하, 백화, 점, 가격, 반, 가격, 구입, 0, 0, 0, ...</td>
      <td>[9, 8, 7, 6]</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>17885</th>
      <td>흠집이 잘 나지 않는 재질같아요\nE0등급이라 맘에 들고요\n숫자에 약해서 사진으로...</td>
      <td>[올리, 느끼, 생각, 작, 그런데, 놓, 에어, 때문, 설치, 서기, 프라이어]</td>
      <td>[흠, 집, 날, 않, 재질, 같, e, 0, 등급, 이, 맘, 듣, 숫자, 약하,...</td>
      <td>[30, 21, 19, 20, 22, 31, 28, 18, 23, 27, 29]</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>11509</th>
      <td>그럭저럭..\n페이스는별로..광고를 페이스에도 좋다고 하는건 좀..ㅠㅠ\n바디는 괜...</td>
      <td>[ㅠㅠ, 것, 괜찮, 하]</td>
      <td>[페이스, 광고, 페이스, 좋, 하, 것, ㅠㅠ, 바디, 괜찮, 0, 0, 0, 0...</td>
      <td>[6, 5, 8, 4]</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>7998</th>
      <td>견미리 팩트 넘 좋아서 3년째\n쓰고 있습니다~^^</td>
      <td>[있, 쓸, 견미리]</td>
      <td>[견미리, 팩, 트, 좋, 3, 년, 쓸, 있, 0, 0, 0, 0, 0, 0, 0...</td>
      <td>[7, 6, 0]</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>2741</th>
      <td>■° 버건디 칼라 괜찮아서,  하나 더 구매 합니다~*  다만, 기모가 엄청 엄청 ...</td>
      <td>[세탁, 빠지, 것, 묻어나, 기모, 달]</td>
      <td>[버, 것, 이, 칼라, 괜찮, 하나, 구매, 하, 다만, 기모, 묻어나, 세탁, ...</td>
      <td>[11, 12, 14, 10, 9, 13]</td>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <th>17782</th>
      <td>집에서 막쓰고 좋아요~잘못사면 너무 얇아서 좋지 않은경우가 있는데 베베숲은 믿고 쓰...</td>
      <td>[이, 제품, 쓸, 경우, 있, 숲]</td>
      <td>[집, 막, 쓸, 좋, 살, 얇, 좋, 않, 경우, 있, 베베, 숲, 믿, 쓸, 제...</td>
      <td>[15, 14, 13, 8, 9, 11]</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>10803</th>
      <td>홈쇼핑에서 처음 속옷사보는데 진짜 괜찮네요...! 구성도 좋고 움직이기 넘 편해요!...</td>
      <td>[작, 때, 보이, 들어가, 늘어나, 것, 펼치, 같, 보정, 싶, 걱정]</td>
      <td>[홈, 쇼핑, 처음, 속, 옷, 사, 보, 괜찮, 구성, 좋, 움직이, 편하, 다만...</td>
      <td>[15, 14, 16, 17, 26, 27, 13, 28, 19, 18, 29]</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>12127</th>
      <td>초3 140센치인데 150 잘맞네요^^\r\n아주 두껍진않아서 요즘 입기 딱좋아요\...</td>
      <td>[센치, 좋, 150, 이, 입]</td>
      <td>[3, 140, 센치, 이, 150, 맞, 두껍, 않, 입, 좋, 저렴, 빠르, 배...</td>
      <td>[2, 9, 4, 3, 8]</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>7547</th>
      <td>정품맞는가?어디 벌크로 파는거 같이  케이스도 없이 바로 뽁뽁이 포장만 허접함.</td>
      <td>[정품, 허접, 포장]</td>
      <td>[정품, 맞, 어디, 팔, 것, 케이스, 포장, 허접, 0, 0, 0, 0, 0, ...</td>
      <td>[0, 7, 6]</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>5130</th>
      <td>먼저 쓰던 가스레인지보다 작아요  뭐든 데워 먹을수 있는 크기라 만족합니다</td>
      <td>[크, 수, 기, 먹, 이]</td>
      <td>[쓸, 가스, 레인지, 작, 뭣, 이, 데우, 먹, 수, 있, 크, 기, 이, 만족...</td>
      <td>[10, 8, 11, 7, 12]</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>9514<

In [43]:
tp = len(df.loc[(df.y == 1) & (df.pred == 1)])
fp = len(df.loc[(df.y == 0) & (df.pred == 1)])
tn = len(df.loc[(df.y == 1) & (df.pred == 0)])
fn = len(df.loc[(df.y == 0) & (df.pred == 0)])

In [44]:
len(df.loc[(df.correct == True)]) / len(df)

0.8373958333333333

In [45]:
pr_0 = fn / (fp + fn)
rc_0 = fn / (tn + fn)
f1_0 = 2*pr_0*rc_0/(pr_0+rc_0)
f1_0

0.6591703056768559

In [46]:
pr_1 = tp / (tp + tn)
rc_1 = tp / (tp + fp)
f1_1 = 2*pr_1*rc_1/(pr_1+rc_1)
f1_1

0.8932284541723667

In [53]:
from itertools import chain
from collections import Counter

In [76]:
alpha_tokens = df.loc[(df.correct == True) & (df.y == 1)].alpha_tokens.tolist()
# chain()
counter = Counter(chain(*alpha_tokens))

In [77]:
import operator
alpha_count = sorted(counter.items(), key=operator.itemgetter(1))

In [78]:
alpha_count.reverse()

In [79]:
alpha_count

[('좋', 4684),
 ('하', 2533),
 ('것', 2298),
 ('이', 2151),
 ('같', 1457),
 ('있', 1258),
 ('않', 830),
 ('배송', 811),
 ('입', 771),
 ('사이즈', 711),
 ('되', 643),
 ('쓰', 640),
 ('크', 631),
 ('가격', 627),
 ('지', 588),
 ('사', 565),
 ('없', 564),
 ('디자인', 551),
 ('쓸', 535),
 ('구입', 529),
 ('제품', 524),
 ('듯', 512),
 ('보', 498),
 ('수', 451),
 ('괜찮', 366),
 ('구매', 349),
 ('주문', 337),
 ('색상', 336),
 ('만족', 334),
 ('오', 323),
 ('때', 309),
 ('피부', 306),
 ('사용', 291),
 ('편하', 279),
 ('살', 276),
 ('옷', 269),
 ('생각', 261),
 ('맘', 260),
 ('나', 243),
 ('마음', 243),
 ('나오', 243),
 ('이쁘', 240),
 ('감사', 232),
 ('상품', 231),
 ('느낌', 227),
 ('색', 218),
 ('주', 217),
 ('듣', 215),
 ('대비', 206),
 ('촉촉', 200),
 ('듭니다', 199),
 ('받', 189),
 ('번', 187),
 ('겨울', 186),
 ('보이', 184),
 ('기대', 173),
 ('개', 172),
 ('알', 170),
 ('빠르', 165),
 ('신', 164),
 ('작', 159),
 ('완전', 157),
 ('들', 156),
 ('품', 154),
 ('날', 152),
 ('하나', 152),
 ('아니', 149),
 ('향', 146),
 ('가볍', 145),
 ('감', 143),
 ('예쁘', 142),
 ('바르', 142),
 ('싸', 138),
 ('딸', 1