In [1]:
import pandas as pd
import numpy as np
import pickle

In [2]:
df_result = pd.read_pickle('df_result.pkl')
df_test = pd.read_pickle('df_test.pkl')
with open('word_index.pkl', 'rb') as pkl_file:
    vocab_dict = pickle.load(pkl_file)

In [4]:
vocab_list = [x for x in range(len(vocab_dict)+1)]
for k,v in vocab_dict.items():
    vocab_list[v] = k

In [5]:
df_test = df_test.head(len(df_result)).reset_index(drop=True)
# df_test.x = df_test.x.apply(lambda x: x.split())
df_test = df_test.rename({'x': 'origin_tokens'}, axis=1)

In [6]:
pd.Series(df_result.y == df_test.y).unique()

array([ True])

In [7]:
len(df_test)

15232

In [8]:
df = pd.concat([df_result, df_test.drop(['y'], axis=1)], axis=1)

In [9]:
df['tokens'] = df.x.apply(lambda x_list: [vocab_list[x] for x in x_list])

In [11]:
df[['text', 'y', 'pred']].head(20)

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>text</th>
      <th>y</th>
      <th>pred</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>상품은 그런데로^^^같이 보내준사은품은 허리도너무크고 교환이 별도로  될런지 모르겠네요</td>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <th>1</th>
      <td>정말 따뜻하고 가볍고 예뻐요 색까지 실제색이 너무 마음에 들었고 호주머니 자크의 견...</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>2</th>
      <td>빠른배송 가격대비 제품만족</td>
      <td>0</td>
      <td>1</td>
    </tr>
    <tr>
      <th>3</th>
      <td>예전부터 사고싶었던 다비네스 가격이 비싸 못샀는데 여기서 세일해서 바로 구매~~  ...</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>4</th>
      <td>싼가격에 깨끗한  신발이 와서 넘 조아요</td>
      <td>0</td>
      <td>1</td>
    </tr>
    <tr>
      <th>5</th>
      <td>좋아요~~ 아이가 사용하는데 끈적임 없고 발림성도 좋고 매끈하네요.. 보습력도 짱~~^^</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>6</th>
      <td>받자마자 냄새가 나서 세탁후착용합니다....\n좋아요....</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>7</th>
      <td>사용해보니 정말 편리하고 좋아요 시야확보가 필요하면 커튼처럼 스르륵~~ 재구매 의향...</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>8</th>
      <td>처음 써보는데 인기가 많은 이유가 있었네요~\n리필 꼭 보내주세요~~</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>9</th>
      <td>딸아이가 좋아하네요\n필요한거라구</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>10</th>
      <td>겨울에 신으려고 구매했어요 발등 바닥 발목까지 털이있어서 아주 따뜻하겠어요 신발맡창...</td>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <th>11</th>
      <td>아주 작은건 아니고, 데일리로 착용하기엔 좋은 사이즈 입니다.깜찍하네요</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>12</th>
      <td>예전엔 이런 기획이 많아 샀던것같은데\n이번에 백화점서 직접 보고 혹시나하고 지에스...</td>
      <td>0</td>
      <td>1</td>
    </tr>
    <tr>
      <th>13</th>
      <td>찌든때까지는 깨끗하게 씻기진 않지만 간단하게 욕실 청소 매일 손쉽게 할 수 있어서 ...</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>14</th>
      <td>매장에서보다 저렴하게 샀어요. 배송도 빠르고. 제품도 무난하게 좋습니다.</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>15</th>
      <td>드라이기를 이가격에 사는것이 고민되긴 하였지만 너무 만족스럽게 사용하고 있어요  빠...</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>16</th>
      <td>맘에들어요  매트커버도 주문해야겠네요</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>17</th>
      <td>보들 보들 예뻐요 11세 155 사이즈 5세 110사이즈 낙낙하게 잘 맞네요..</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>18</th>
      <td>지금 받았습니다. 막 써보니 향도 좋네요.</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>19</th>
      <td>제가 추천하는 티슈입니다.\n이것저것 다 써봤지만 이 상품이\n제일 마음에 들어요.</td>
      <td>1</td>
      <td>1</td>
    </tr>
  </tbody>
</table>
</div>

In [12]:
def get_max_args(row):
    alpha = np.array(row['alpha'])
    x =  np.array(row['x'])
    zero_index = np.where(x == 0)[0].tolist()
    if zero_index:
        sent_size = int(zero_index[0])
    else:
        sent_size = int(len(x))
    num_alpha = int(sent_size / 3) + 1
    alpha = alpha[:sent_size].argsort()[-num_alpha:][::-1]
    return alpha.tolist()


df['max_args'] = df.apply(lambda row: get_max_args(row), axis=1)

In [13]:
print(np.argsort([1, 3, 2, 4, 5]))
print(np.argsort([1, 3, 2, 4, 5])[-3:])
print(np.argsort([1, 3, 2, 4, 5])[-3:][::-1])

print(np.where(np.array([1,3] )== 0)[0])
# 1 2 0 / 2 0 1

[0 2 1 3 4]
[1 3 4]
[4 3 1]
[]


In [14]:
df.x.values[0]

array([  49,   70,   92,   26,  206,   91,  174,   19,  103, 2173,   13,
        111,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
      dtype=int32)

In [15]:
df[['tokens', 'x','max_args']].head(20)

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>tokens</th>
      <th>x</th>
      <th>max_args</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>[상품, 데, 보내, 주, 사은, 품, 허리, 크, 교환, 별도, 되, 모르, 0,...</td>
      <td>[49, 70, 92, 26, 206, 91, 174, 19, 103, 2173, ...</td>
      <td>[11, 9, 10, 8, 4]</td>
    </tr>
    <tr>
      <th>1</th>
      <td>[따뜻, 가볍, 예쁘, 색, 실제, 색, 마음, 듣, 호, 주머니, 자크, 견고, ...</td>
      <td>[32, 60, 33, 58, 1122, 58, 90, 30, 219, 473, 2...</td>
      <td>[26, 27, 22, 25, 21, 23, 24, 20, 31, 19, 29]</td>
    </tr>
    <tr>
      <th>2</th>
      <td>[빠르, 배송, 가격, 대비, 제품, 만족, 0, 0, 0, 0, 0, 0, 0, ...</td>
      <td>[45, 17, 16, 81, 14, 22, 0, 0, 0, 0, 0, 0, 0, ...</td>
      <td>[3, 5, 2]</td>
    </tr>
    <tr>
      <th>3</th>
      <td>[예전, 살, 싶, 다비, 네스, 가격, 비싸, 사, 여기, 세일, 구매, 분사, ...</td>
      <td>[439, 40, 67, 2673, 2725, 16, 210, 23, 353, 82...</td>
      <td>[25, 24, 23, 22, 20, 21, 16, 6, 18]</td>
    </tr>
    <tr>
      <th>4</th>
      <td>[싸, 가격, 깨끗, 신발, 오, 조아, 이, 0, 0, 0, 0, 0, 0, 0,...</td>
      <td>[75, 16, 419, 139, 37, 346, 1, 0, 0, 0, 0, 0, ...</td>
      <td>[1, 3, 0]</td>
    </tr>
    <tr>
      <th>5</th>
      <td>[좋, 아이, 사용, 데, 끈적이, 없, 발림, 좋, 매끈, 보습, 짱, 0, 0,...</td>
      <td>[2, 69, 10, 70, 556, 20, 292, 2, 1225, 429, 18...</td>
      <td>[10, 9, 2, 1]</td>
    </tr>
    <tr>
      <th>6</th>
      <td>[받, 냄새, 나, 세탁, 후, 착용, 좋, 0, 0, 0, 0, 0, 0, 0, ...</td>
      <td>[29, 150, 47, 175, 102, 147, 2, 0, 0, 0, 0, 0,...</td>
      <td>[3, 2, 4]</td>
    </tr>
    <tr>
      <th>7</th>
      <td>[사용, 보, 편리, 좋, 확보, 필요, 커튼, 구매, 의향, 있, 0, 0, 0,...</td>
      <td>[10, 6, 477, 2, 4727, 194, 1343, 11, 3221, 5, ...</td>
      <td>[8, 7, 9, 6]</td>
    </tr>
    <tr>
      <th>8</th>
      <td>[쓰, 보, 인기, 많, 이유, 있, 리필, 보내, 주, 0, 0, 0, 0, 0,...</td>
      <td>[15, 6, 2395, 94, 583, 5, 598, 92, 26, 0, 0, 0...</td>
      <td>[8, 7, 1, 6]</td>
    </tr>
    <tr>
      <th>9</th>
      <td>[딸, 아이, 좋, 않, 필요, 것, 이, 0, 0, 0, 0, 0, 0, 0, 0...</td>
      <td>[98, 69, 2, 9, 194, 4, 1, 0, 0, 0, 0, 0, 0, 0,...</td>
      <td>[5, 4, 3]</td>
    </tr>
    <tr>
      <th>10</th>
      <td>[겨울, 신, 구매, 발, 등, 바닥, 발, 목, 털, 있, 따뜻, 신발, 맡, 미...</td>
      <td>[44, 52, 11, 66, 200, 232, 66, 112, 89, 5, 32,...</td>
      <td>[19, 18, 16, 15, 14, 17, 12]</td>
    </tr>
    <tr>
      <th>11</th>
      <td>[작, 것, 아니, 데일리, 착용, 좋, 사이즈, 이, 깜찍, 0, 0, 0, 0,...</td>
      <td>[57, 4, 48, 858, 147, 2, 18, 1, 1717, 0, 0, 0,...</td>
      <td>[2, 1, 4, 3]</td>
    </tr>
    <tr>
      <th>12</th>
      <td>[예전, 기획, 많, 사, 것, 같, 이, 번, 백화, 점, 보, 지에스, 들어오,...</td>
      <td>[439, 2189, 94, 23, 4, 8, 1, 27, 561, 230, 6, ...</td>
      <td>[30, 31, 29, 24, 26, 1, 27, 21, 25, 28, 4]</td>
    </tr>
    <tr>
      <th>13</th>
      <td>[찌들, 때, 깨끗, 씻기, 않, 간단, 욕실, 청소, 손쉽, 하, 수, 있, 편하...</td>
      <td>[3540, 38, 419, 3015, 9, 1096, 1416, 404, 4177...</td>
      <td>[4, 5, 0, 12, 11]</td>
    </tr>
    <tr>
      <th>14</th>
      <td>[매장, 저렴, 사, 배송, 빠르, 제품, 무난, 좋, 0, 0, 0, 0, 0, ...</td>
      <td>[554, 46, 23, 17, 45, 14, 282, 2, 0, 0, 0, 0, ...</td>
      <td>[0, 6, 1]</td>
    </tr>
    <tr>
      <th>15</th>
      <td>[드라, 이기, 가격, 살, 것, 고민, 않, 만족, 사용, 있, 빠르, 말리, 수...</td>
      <td>[2215, 2273, 16, 40, 4, 127, 9, 22, 10, 5, 45,...</td>
      <td>[8, 7, 12, 6, 2, 14]</td>
    </tr>
    <tr>
      <th>16</th>
      <td>[맘, 듣, 매트, 커버, 주문, 하, 0, 0, 0, 0, 0, 0, 0, 0, ...</td>
      <td>[31, 30, 411, 177, 24, 3, 0, 0, 0, 0, 0, 0, 0,...</td>
      <td>[5, 3, 0]</td>
    </tr>
    <tr>
      <th>17</th>
      <td>[예쁘, 11, 세, 155, 사이즈, 5, 세, 110, 사이즈, 낙낙, 맞, 0...</td>
      <td>[33, 668, 345, 1553, 18, 222, 345, 1184, 18, 7...</td>
      <t

In [16]:
def get_alpha_tokens(row):
    max_args = row['max_args']
    xs = row['x']
    tokens = row['tokens']
    alpha_tokens = list()
    try:
        alpha_tokens = [tokens[arg] for arg in max_args if xs[arg] != 0]
    except IndexError:
        print(tokens)
        print(max_args)
        alpha_tokens = None
    finally:
        return alpha_tokens

df['alpha_tokens'] = df.apply(lambda row: get_alpha_tokens(row), axis=1)

In [17]:
df.loc[13594]

x                [380, 65, 619, 38, 87, 540, 2524, 65, 9, 448, ...
y                                                                1
alpha            [9.768779e-05, 9.443449e-05, 0.00014683574, 9....
pred                                                             1
text             에센스 바르고 말릴때 머리카락 보들보들 거려요~~\n많이 발라야하는지...마르고 나...
origin_tokens    [에센스, 바르, 말리, 때, 머리, 카락, 거려, 바르, 않, 마르, 나, 푸석,...
tokens           [에센스, 바르, 말리, 때, 머리, 카락, 거려, 바르, 않, 마르, 나, 푸석,...
max_args                                 [8, 9, 12, 11, 10, 2, 13]
alpha_tokens                             [않, 마르, 느낌, 푸석, 나, 말리, 있]
Name: 13594, dtype: object

In [21]:
df['correct'] = (df.y == df.pred)

In [22]:
df.loc[(df.correct==True), ['text', 'alpha_tokens', 'tokens', 'max_args', 'y', 'pred']].sample(20)

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>text</th>
      <th>alpha_tokens</th>
      <th>tokens</th>
      <th>max_args</th>
      <th>y</th>
      <th>pred</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>1142</th>
      <td>엄마가 사주라고 해서 사드렸는데 너무 좋아하세요 ㅋㅋㅋㅋㅋ 결제 하기를 잘 했네요 ...</td>
      <td>[나오, 알뜰, 살, 하, 하, 쓸]</td>
      <td>[엄마, 사, 주, 하, 사, 드리, 좋, 않, 결제, 하, 알뜰, 쓸, 나오, 살...</td>
      <td>[12, 10, 13, 14, 9, 11]</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>3826</th>
      <td>허벡지가조금끼네요\n바지는예쁩니다\n더사야겠어요</td>
      <td>[지, 바지, 끼]</td>
      <td>[지, 끼, 바지, 예쁘, 살, 하, 0, 0, 0, 0, 0, 0, 0, 0, 0...</td>
      <td>[0, 2, 1]</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>2949</th>
      <td>어깨통 암홀이 짝짝이고..체크에 누빔이라 그런지 옷태가 세련되어 보이지 않고..사진...</td>
      <td>[실패, 입, 하, 슈퍼, 때, 가, 동네, 그렇, 반품, 대비]</td>
      <td>[어깨, 통, 암홀, 이, 체크, 누비, 이, 그렇, 옷, 세련, 보이, 않, 사진...</td>
      <td>[27, 25, 26, 22, 24, 23, 21, 20, 19, 18]</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>4037</th>
      <td>거의 완벽 합니다.\n가성비 최고.\n마무리 디자인 최고 입니다.\n단,  칫수에 ...</td>
      <td>[좁, 폭, 성비, 디자인, 완벽]</td>
      <td>[완벽, 하, 성비, 최고, 마무리, 디자인, 최고, 이, 수, 선택, 폭, 좁, ...</td>
      <td>[11, 10, 2, 5, 0]</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>5410</th>
      <td>남편이  만족해하네요~ 게다가 싸게 구입해서 더 좋아요</td>
      <td>[싸, 구입, 만족]</td>
      <td>[남편, 만족, 하, 싸, 구입, 좋, 0, 0, 0, 0, 0, 0, 0, 0, ...</td>
      <td>[3, 4, 1]</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>11762</th>
      <td>색상이 약간 밝지만..그래서 톤 업 효과는 확실한듯...</td>
      <td>[듯, 효과, 확실]</td>
      <td>[색상, 밝, 그래서, 톤, 업, 효과, 확실, 듯, 0, 0, 0, 0, 0, 0...</td>
      <td>[7, 5, 6]</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>8048</th>
      <td>요즘 많이 건조했는데 앰플 바르고\r\n톡톡 두드려 주니 흡수도 잘되고\r\n촉촉한...</td>
      <td>[앰, 건조, 주, 바르]</td>
      <td>[건조, 앰, 플, 바르, 두드리, 주, 흡수, 되, 촉촉, 것, 같, 0, 0, ...</td>
      <td>[1, 0, 5, 3]</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>666</th>
      <td>넘 좋아요. 가격도 다른 곳 보다 저렴하고 오자마자 고기 사와서 구워 먹었어요.  ...</td>
      <td>[오, 곳, 굽, 저렴, 오, 좋]</td>
      <td>[좋, 가격, 곳, 저렴, 오, 고기, 사, 오, 굽, 먹, 고기, 맛있, 굽, 지...</td>
      <td>[4, 2, 8, 3, 7, 14]</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>8694</th>
      <td>따뜻하고가볍고디자인좋고..상품평에 크다고해서 많이클줄알았더니 그렇지도않더라구용 적당...</td>
      <td>[맞, 맞, 않, 그렇, 길이, 알, 줄]</td>
      <td>[따뜻, 가볍, 디자인, 좋, 상, 품평, 크, 하, 크, 줄, 알, 그렇, 않, ...</td>
      <td>[13, 14, 12, 11, 15, 10, 9]</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>4655</th>
      <td>문 앞에 떨어져 있길래 잘 주워 들였습니다.\nmade in china  별로 싸다...</td>
      <td>[싸, 들, 앞, 생각]</td>
      <td>[문, 앞, 떨어지, 있, 줍, 들이, 싸, 생각, 들, 0, 0, 0, 0, 0,...</td>
      <td>[6, 8, 1, 7]</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>2310</th>
      <td>정사이즈가 추천이고 엄청 따뜻해요 꽤나 두껍네요</td>
      <td>[정, 사이즈, 추천]</td>
      <td>[정, 사이즈, 추천, 이, 따뜻, 두껍, 0, 0, 0, 0, 0, 0, 0, 0...</td>
      <td>[0, 1, 2]</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>2529</th>
      <td>쓰던 제품이 안나와서 모험심으로 샀는데, 만족합니다~</td>
      <td>[심, 만족, 사]</td>
      <td>[쓸, 제품, 나오, 심, 사, 만족, 0, 0, 0, 0, 0, 0, 0, 0, ...</td>
      <td>[3, 5, 4]</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>3825</th>
      <td>베개 강추입니다.\n부드럽고 푹신하고\n참 편하네요\n만족합니다</td>
      <td>[개, 베, 강추]</td>
      <td>[베, 개, 강추, 이, 부드럽, 푹신, 편하, 만족, 0, 0, 0, 0, 0, ...</td>
      <td>[1, 0, 2]</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>2865</th>
      <td>무지 쨍쨍해요 내가 언제 살이 쪘지 싶어요 ㅋㅋ\n이쁘긴 이쁘네용~ 그리고 브라패드...</td>
      <td>[참고, 입, 되, 넣, 내, 하]</td>
      <td>[하, 내, 살, 찌, 싶,

In [44]:
tp = len(df.loc[(df.y == 1) & (df.pred == 1)])
fp = len(df.loc[(df.y == 0) & (df.pred == 1)])
tn = len(df.loc[(df.y == 1) & (df.pred == 0)])
fn = len(df.loc[(df.y == 0) & (df.pred == 0)])

In [45]:
len(df.loc[(df.correct == True)]) / len(df)

0.8321297268907563

In [46]:
pr_0 = fn / (fp + fn)
rc_0 = fn / (tn + fn)
f1_0 = 2*pr_0*rc_0/(pr_0+rc_0)
f1_0

0.624246877296106

In [47]:
pr_1 = tp / (tp + tn)
rc_1 = tp / (tp + fp)
f1_1 = 2*pr_1*rc_1/(pr_1+rc_1)
f1_1

0.8919227355340462

In [48]:
(f1_1 + f1_0)/2

0.758084806415076